name: 'Test CI/CD Pipeline to demonstrate build and deploy'

on: 
  push:
    branches: [ "main" ]
    paths:  
        - '**'
    # paths-ignore:
    #     - 'README.md'
#   pull_request:
#     branches: [ "main" ]
    # paths:
    #     - '**'

# on:
#   workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  Build: 
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with: 
            fetch-depth: 0
  
        - name: Setup Azure CLI
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Run Bicep What-If
          run: |
                az deployment group what-if --resource-group ${{ vars.AZURE_RESOURCEGROUP_TEST }} \
                  --template-file ./main.bicep \
                  --parameters ./main.bicepparam \
                    location='${{ vars.AZURE_LOCATION }}' \
                  --mode Incremental

  DeployTst:
    name: Deploy to Test
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
            fetch-depth: 0

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Bicep What-If
        run: |
            az deployment group what-if --resource-group ${{ vars.AZURE_RESOURCEGROUP_TEST }} \
              --template-file ./main.bicep \
              --parameters ./main.bicepparam \
                location='${{ vars.AZURE_LOCATION }}' \
              --mode Incremental
            

      - name: Run Bicep create
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
            az deployment group create --resource-group ${{ vars.AZURE_RESOURCEGROUP_TEST }} \
              --template-file ./main.bicep \
              --parameters ./main.bicepparam \
                location='${{ vars.AZURE_LOCATION }}' \
              --mode Incremental

  DeployProd:
    name: Deploy to Prod
    needs: [DeployTst]
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Bicep What-If
        run: |
            az deployment group what-if --resource-group ${{ vars.AZURE_RESOURCEGROUP_PROD }} \
              --template-file ./main.bicep \
              --parameters ./main.bicepparam \
                location='${{ vars.AZURE_LOCATION }}' \
              --mode Incremental
            

      - name: Run Bicep create
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
            az deployment group create --resource-group ${{ vars.AZURE_RESOURCEGROUP_PROD }} \
              --template-file ./main.bicep \
              --parameters ./main.bicepparam \
                location='${{ vars.AZURE_LOCATION }}' \
              --mode Incremental